name: "poc_project"
version: "1.0"
config-version: 2

profile: "default"

models:
  poc_project:
    # materialized: table
    stg:
      schema: stg
    dwd:
      schema: dwd
    mart:
      schema: mart
